# Generated by Django 2.1.1 on 2018-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='title:'),
        ),
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.TextField(blank=True, verbose_name='Share Something:'),
        ),
    ]
