# Generated by Django 2.1.1 on 2018-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180930_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='share',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
