# Generated by Django 2.1.1 on 2018-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181001_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(max_length=250, null=True, verbose_name='Message:'),
        ),
    ]
