# Generated by Django 2.1.1 on 2018-10-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181001_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
    ]
