# Generated by Django 2.1.1 on 2018-10-01 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20181001_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 11, 17, 10, 9178), null=True),
        ),
    ]
