# Generated by Django 2.1.1 on 2018-10-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20181001_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 11, 21, 45, 140984), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(max_length=450, null=True, verbose_name=''),
        ),
    ]
