# Generated by Django 2.1.1 on 2018-10-02 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20181001_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 9, 33, 9, 779059), null=True),
        ),
    ]
