# Generated by Django 2.1.1 on 2018-10-03 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20181002_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 12, 21, 57, 858387), null=True),
        ),
    ]
