# Generated by Django 2.1.1 on 2018-10-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20181003_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 22, 39, 7, 983340), null=True),
        ),
    ]
