# Generated by Django 2.1.1 on 2018-10-03 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20181003_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 22, 44, 37, 662720), null=True),
        ),
    ]
