# Generated by Django 2.1.1 on 2018-10-05 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20181004_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 17, 24, 13, 8513), null=True),
        ),
    ]
