# Generated by Django 2.1.1 on 2018-09-24 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transexual', 'Trans'), ('Intersex', 'Intersex'), ('Non-Binary', 'Non-Binary'), ('Rather not say', 'Rather not answer')], max_length=50)),
                ('age', models.IntegerField()),
                ('Nationality', models.CharField(blank=True, choices=[('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangldeshi'), ('Sri Lankan', 'Sri Lankan'), ('Arab', 'Arab'), ('White', 'White'), ('Black', 'Black'), ('other', 'other')], max_length=100, null=True, verbose_name='Ethnicity:')),
                ('image', models.ImageField(null=True, upload_to='pic_folder/', verbose_name='your profile photo (required):')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='your height in cms:')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Your weight in kgs:')),
                ('description', models.TextField(max_length=500, verbose_name='Introduce yourself:')),
                ('lookingfor', models.TextField(max_length=500, verbose_name='Your ideal soulmate:')),
                ('preference', models.CharField(choices=[('gay man looking for another gay man', 'gay man looking for another gay man'), ('bisexual man looking for men and women', 'bisexual man looking for men and women'), ('gay man looking for a lesbian wife', 'gay man looking for a lesbian wife'), ('lesbian woman looking for another lesbian woman', 'lesbian woman looking for another lesbian woman'), ('bisexual woman looking for both men and women', 'bisexual woman looking for both men and women'), ('lesbian woman looking for a gay husband', 'lesbian woman looking for a gay husband'), ('trans/intersex looking for females', 'trans/intersex looking for females'), ('trans/intersex looking for males', 'trans/intersex looking for males'), ('male looking for trans/intersex', 'male looking for trans/intersex'), ('female looking for trans/intersex', 'female looking for trans/intersex')], max_length=300, null=True, verbose_name='Preference:')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
