# Generated by Django 2.1.1 on 2018-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='Nationality',
            field=models.CharField(blank=True, choices=[('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Sri Lankan', 'Sri Lankan'), ('Arab', 'Arab'), ('White', 'White'), ('Black', 'Black'), ('Asian', 'Asian'), ('other', 'other')], max_length=100, null=True, verbose_name='Ethnicity:'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Intersex', 'Intersex'), ('Non-Binary', 'Non-Binary'), ('Rather not say', 'Rather not say')], max_length=50),
        ),
    ]
