# Generated by Django 2.1.1 on 2018-09-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180926_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
