# Generated by Django 2.1.1 on 2018-09-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofiles_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='created',
        ),
    ]
