# Generated by Django 2.1.1 on 2018-10-01 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180928_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
