# Generated by Django 2.1.1 on 2018-10-03 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20181003_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
